/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

/**
 *
 * @author jafes
 */
public class ConfirmarPedido extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmarPedido
     */
    public ConfirmarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSumaDeOrdenes = new javax.swing.JLabel();
        txtSumaOrdenes = new javax.swing.JTextField();
        lblPrecioDomicilio = new javax.swing.JLabel();
        txtPrecioDomicilio = new javax.swing.JTextField();
        lblImpuestoRestaurante = new javax.swing.JLabel();
        txtImpuestoRestaurante = new javax.swing.JTextField();
        lblTOTAL = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        btnCancelarPedido = new javax.swing.JButton();
        btnPagarPedido = new javax.swing.JButton();

        lblSumaDeOrdenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSumaDeOrdenes.setText("SUMA DE LAS ORDENES: ");

        txtSumaOrdenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPrecioDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrecioDomicilio.setText("PRECIO DEL DOMICILIO: ");

        txtPrecioDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblImpuestoRestaurante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImpuestoRestaurante.setText("IMPUESTO AL PEDIDO: ");

        txtImpuestoRestaurante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTOTAL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTOTAL.setForeground(new java.awt.Color(255, 0, 0));
        lblTOTAL.setText("TOTAL:");

        txtTOTAL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTOTAL.setForeground(new java.awt.Color(255, 0, 0));

        btnCancelarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarPedido.setText("CANCELAR PEDIDO");

        btnPagarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPagarPedido.setText("PAGAR PEDIDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSumaDeOrdenes)
                        .addComponent(lblPrecioDomicilio)
                        .addComponent(lblImpuestoRestaurante)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(lblTOTAL)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImpuestoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSumaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSumaDeOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSumaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioDomicilio)
                    .addComponent(txtPrecioDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuestoRestaurante)
                    .addComponent(txtImpuestoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTOTAL)
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPedido)
                    .addComponent(btnPagarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnPagarPedido;
    private javax.swing.JLabel lblImpuestoRestaurante;
    private javax.swing.JLabel lblPrecioDomicilio;
    private javax.swing.JLabel lblSumaDeOrdenes;
    private javax.swing.JLabel lblTOTAL;
    private javax.swing.JTextField txtImpuestoRestaurante;
    private javax.swing.JTextField txtPrecioDomicilio;
    private javax.swing.JTextField txtSumaOrdenes;
    private javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
