/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import static co.unicauca.microkernel.client.access.Factory.getInstance;
import co.unicauca.microkernel.client.access.IClienteAccess;
import co.unicauca.microkernel.client.domain.clienteService;
import co.unicauca.microkernel.common.entities.PlatoEspecial;
import co.unicauca.microkernel.common.entities.RacionDia;
import co.unicauca.microkernel.common.infra.Utilities;
import static co.unicauca.microkernel.client.gestionTabla.StructEspeciales.DESCRIPCION;
import static co.unicauca.microkernel.client.gestionTabla.StructEspeciales.ID;
import static co.unicauca.microkernel.client.gestionTabla.StructEspeciales.NOMBRE;
import static co.unicauca.microkernel.client.gestionTabla.StructEspeciales.PRECIO;
import static co.unicauca.microkernel.client.gestionTabla.StructRaciones.DIA;
import static co.unicauca.microkernel.client.gestionTabla.StructRaciones.TIPO;
import co.unicauca.microkernel.client.gestionTabla.TablaEspeciales;
import co.unicauca.microkernel.client.gestionTabla.TablaRaciones;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import static java.lang.System.out;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import static java.util.logging.Level.SEVERE;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author EdynsonMJ
 */
public class FramePrincipalAdmin extends javax.swing.JFrame {

    //listas
    List<RacionDia> raciones;
    List<PlatoEspecial> especiales;
    //tablas
    TablaRaciones tabRaciones;
    TablaEspeciales tabEspeciales;
    //servicio
    IClienteAccess service;
    clienteService servicioRestaurante;
    //variables
    private static List<String> idRestaurante;
    private String varDia;
    private int idSeleccionado;
    private String photoNull;

    /**
     * Creates new form FramePrincipalAdmin
     * @param idRestaurantes
     */
    public FramePrincipalAdmin(List<String> idRestaurantes) {
        try {
            idRestaurante=idRestaurantes;
            //INSTANCIANDO EL SERVICIO, POR FABRICA
            service = getInstance().getClienteService();
            servicioRestaurante = new clienteService(service);
            //INICIALIZANDO TABLAS
            tabRaciones = new TablaRaciones();
            tabEspeciales = new TablaEspeciales();
            //INICIANDO COMPONENENTES
            initComponents();
            //INICIALIZANDO TABLAS Y LLENANDO LISTAS
            raciones = new ArrayList<>();
            especiales = new ArrayList<>();
            this.crearIndexRestaurante();
            lblNomUsu.setText(idRestaurantes.get(idRestaurantes.size()-1));
            varDia="TODOS";
            photoNull="\\Restaurant\\Restaurante-cliente\\src\\main\\java\\imagenes\\photoNotAvailable.jpg";
        } catch (Exception ex) {
            getLogger(FramePrincipalAdmin.class.getName()).log(SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpPestanias = new javax.swing.JTabbedPane();
        pnlInicio = new javax.swing.JPanel();
        lblImagenInicio = new javax.swing.JLabel();
        pnlInfoUsuario = new javax.swing.JPanel();
        lblImagenUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblNombreRestaurante = new javax.swing.JLabel();
        cbxRestaurante = new javax.swing.JComboBox<>();
        lblNomUsu = new javax.swing.JLabel();
        pnlRaciones = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRaciones = new javax.swing.JTable();
        lblImagenRacion = new javax.swing.JLabel();
        btnAgregarRacion = new javax.swing.JButton();
        pnlEspeciales = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEspeciales = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblImagenEspecial = new javax.swing.JLabel();
        pnlPedidos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreUsuario.setText("Nombre: ");

        lblNombreRestaurante.setText("Restaurante:");

        cbxRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRestauranteActionPerformed(evt);
            }
        });

        lblNomUsu.setText("---------------------");

        javax.swing.GroupLayout pnlInfoUsuarioLayout = new javax.swing.GroupLayout(pnlInfoUsuario);
        pnlInfoUsuario.setLayout(pnlInfoUsuarioLayout);
        pnlInfoUsuarioLayout.setHorizontalGroup(
            pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNomUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxRestaurante, 0, 160, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlInfoUsuarioLayout.setVerticalGroup(
            pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(lblNomUsu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRestaurante)
                    .addComponent(cbxRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(pnlInfoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInfoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagenInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("INICIO", pnlInicio);

        lblFiltro.setText("Filtar por dia:");

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO" }));
        cbxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaActionPerformed(evt);
            }
        });

        tblRaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DIA", "TIPO", "PRECIO", "ACCION 1", "ACCION 2"
            }
        ));
        tblRaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRaciones);
        if (tblRaciones.getColumnModel().getColumnCount() > 0) {
            tblRaciones.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        btnAgregarRacion.setText("AGREGAR");

        javax.swing.GroupLayout pnlRacionesLayout = new javax.swing.GroupLayout(pnlRaciones);
        pnlRaciones.setLayout(pnlRacionesLayout);
        pnlRacionesLayout.setHorizontalGroup(
            pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRacionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRacionesLayout.createSequentialGroup()
                        .addComponent(lblFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImagenRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        pnlRacionesLayout.setVerticalGroup(
            pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltro))
                .addGap(18, 18, 18)
                .addGroup(pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("RACIONES", pnlRaciones);

        tblEspeciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "PRECIO", "ACCION 1", "ACCION 1"
            }
        ));
        tblEspeciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEspecialesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEspeciales);
        if (tblEspeciales.getColumnModel().getColumnCount() > 0) {
            tblEspeciales.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jButton1.setText("AGREGAR");

        javax.swing.GroupLayout pnlEspecialesLayout = new javax.swing.GroupLayout(pnlEspeciales);
        pnlEspeciales.setLayout(pnlEspecialesLayout);
        pnlEspecialesLayout.setHorizontalGroup(
            pnlEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblImagenEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEspecialesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        pnlEspecialesLayout.setVerticalGroup(
            pnlEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagenEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("PLATOS ESPECIALES", pnlEspeciales);

        jLabel4.setText("PEDIDOS");

        javax.swing.GroupLayout pnlPedidosLayout = new javax.swing.GroupLayout(pnlPedidos);
        pnlPedidos.setLayout(pnlPedidosLayout);
        pnlPedidosLayout.setHorizontalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        pnlPedidosLayout.setVerticalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel4)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("PEDIDOS", pnlPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpPestanias)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPestanias, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRacionesMouseClicked
        int column = tblRaciones.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblRaciones.getRowHeight();
        byte[] imagen = this.raciones.get(row).getImagen();
        //INSTANCIAR IMAGEN
        if (imagen != null) {
            this.lblImagenRacion.setIcon(this.fijarImagen(imagen,lblImagenRacion.getWidth(),lblImagenRacion.getHeight()));
        } else {
            this.lblImagenRacion.setIcon(this.fijarImagen(Utilities.convertirFoto(photoNull)
                    ,lblImagenRacion.getWidth(),lblImagenRacion.getHeight()));
        }
        if (row < tblRaciones.getRowCount() && row >= 0 && column < tblRaciones.getColumnCount() && column >= 0) {
            Object value = tblRaciones.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                var boton = (JButton) value;
                if (boton.getName().equals("modificar")) {
                    //es obtendra la informacion necesaria para construir un objeto que sera enviado a la interfaz modificar
                    out.println("Click en el boton modificar");
                    out.println(this.tblRaciones.getValueAt(row, ID));
                    out.println(this.tblRaciones.getValueAt(row, NOMBRE));
                    out.println(this.tblRaciones.getValueAt(row, PRECIO));
                    out.println(this.tblRaciones.getValueAt(row, TIPO));
                    out.println(this.tblRaciones.getValueAt(row, DIA));
                }
                if (boton.getName().equals("eliminar")) {
                    int fila = tblRaciones.getSelectedRow();
                    int clave = this.raciones.get(fila).getRacId();
                    try {
                        if ((JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que quiere eliminar la racion \""
                                + this.raciones.get(fila).getNombre()
                                + "\"?", "Eliminar Registro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)) == JOptionPane.YES_OPTION) {
                            if (this.servicioRestaurante.deleteRacionDia(clave).equals("FALLO")) {
                                JOptionPane.showMessageDialog(rootPane, "El registro no existe");
                            } else {
                                this.lblImagenRacion.setIcon(this.fijarImagen(Utilities.convertirFoto(photoNull)
                                        ,lblImagenRacion.getWidth(),lblImagenRacion.getHeight()));
                                this.crearTablaRaciones(varDia);
                                JOptionPane.showMessageDialog(rootPane, "operacion exitosa");
                            }
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(rootPane, "operacion fallida "+ex.getMessage());
                    }
                }
            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                var ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_tblRacionesMouseClicked

    private void tblEspecialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEspecialesMouseClicked
        int column = tblEspeciales.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblEspeciales.getRowHeight();
        byte[] imagen = this.especiales.get(row).getImagen();
        if (imagen != null) {
            this.lblImagenEspecial.setIcon(this.fijarImagen(imagen,lblImagenEspecial.getWidth(),lblImagenEspecial.getHeight()));
        } else {
            this.lblImagenEspecial.setIcon(this.fijarImagen(Utilities.convertirFoto(photoNull)
                    ,lblImagenEspecial.getWidth(),lblImagenEspecial.getHeight()));
        }
        if (row < tblEspeciales.getRowCount() && row >= 0 && column < tblEspeciales.getColumnCount() && column >= 0) {
            Object value = tblEspeciales.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                var boton = (JButton) value;
                if (boton.getName().equals("modificar")) {
                    //es obtendra la informacion necesaria para construir un objeto que sera enviado a la interfaz modificar
                    out.println("Click en el boton modificar");
                    out.println(this.tblEspeciales.getValueAt(row, ID));
                    out.println(this.tblEspeciales.getValueAt(row, NOMBRE));
                    out.println(this.tblEspeciales.getValueAt(row, PRECIO));
                    out.println(this.tblEspeciales.getValueAt(row, DESCRIPCION));
                    //EVENTOS MODIFICAR
                }
                if (boton.getName().equals("eliminar")) {
                    int fila = tblEspeciales.getSelectedRow();
                    int clave = this.especiales.get(fila).getId_pe();
                    try {
                        if ((JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que quiere eliminar el plato \""
                                + this.especiales.get(fila).getNombre()
                                + "\"?", "Eliminar Registro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)) == JOptionPane.YES_OPTION) {
                            if (this.servicioRestaurante.deletePlatoEspecial(clave).equals("FALLO")) {
                                JOptionPane.showMessageDialog(rootPane, "El registro no existe");
                            } else {
                                this.lblImagenEspecial.setIcon(this.fijarImagen(Utilities.convertirFoto(photoNull)
                                        ,lblImagenEspecial.getWidth(),lblImagenEspecial.getHeight()));
                                this.crearTablaEspeciales();
                                JOptionPane.showMessageDialog(rootPane, "operacion exitosa");
                            }
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(rootPane, "operacion fallida");
                    }
                }
            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                var ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_tblEspecialesMouseClicked

    private void cbxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaActionPerformed
        varDia=cbxDia.getSelectedItem().toString();
        try {
            crearTablaRaciones(varDia);
        } catch (Exception ex) {
            Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxDiaActionPerformed

    private void cbxRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRestauranteActionPerformed
        String sel=cbxRestaurante.getSelectedItem().toString();
        for (int i = 0; i < idRestaurante.size()-1; i++) {
            String [] dat =idRestaurante.get(i).split("-");
            if (dat[1].equals(sel)) {
                this.idSeleccionado=Integer.parseInt(dat[0]);
                break;
            }
        }
        
        try {
            this.crearTablaRaciones("TODOS");
            this.crearTablaEspeciales();
        } catch (Exception ex) {
            Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cbxRestauranteActionPerformed

    private void serviceListarRaciones(String varDia) throws Exception {
        if (varDia.equals("TODOS")) {
            this.raciones = servicioRestaurante.listMenuDayAll(idSeleccionado, "administrador");
        }else{
            this.raciones = servicioRestaurante.listMenuDay(idSeleccionado,varDia,"administrador");
        }
    }

    private void serviceListarEspeciales() throws Exception {
        this.especiales = servicioRestaurante.listMenuSpecial(idSeleccionado, "administrador");
    }

    private Icon fijarImagen(byte[] imagen,int anchura,int altura) {
        Icon iconoEscalado;
        var i = new ImageIcon(imagen);
        Image imgEscalada = i.getImage().getScaledInstance(anchura, altura, SCALE_SMOOTH);
        iconoEscalado = new ImageIcon(imgEscalada);
        
        return iconoEscalado;
    }

    private void crearTablaRaciones(String varDia) throws Exception{
        this.tblRaciones.removeAll();
        this.serviceListarRaciones(varDia);
        tabRaciones.ver_tabla(tblRaciones, raciones);
    }

    private void crearTablaEspeciales() throws Exception {
        this.tblEspeciales.removeAll();
        this.serviceListarEspeciales();
        tabEspeciales.ver_tabla(tblEspeciales, especiales);
    }
    private void crearIndexRestaurante(){
        cbxRestaurante.removeAllItems();
        for (int i = 0; i < idRestaurante.size()-1; i++) {
            String [] datos=idRestaurante.get(i).split("-");
            cbxRestaurante.addItem(datos[1]);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>x

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipalAdmin(idRestaurante).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRacion;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxRestaurante;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jtpPestanias;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblImagenEspecial;
    private javax.swing.JLabel lblImagenInicio;
    private javax.swing.JLabel lblImagenRacion;
    private javax.swing.JLabel lblImagenUsuario;
    private javax.swing.JLabel lblNomUsu;
    private javax.swing.JLabel lblNombreRestaurante;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JPanel pnlEspeciales;
    private javax.swing.JPanel pnlInfoUsuario;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JPanel pnlRaciones;
    private javax.swing.JTable tblEspeciales;
    private javax.swing.JTable tblRaciones;
    // End of variables declaration//GEN-END:variables

}
