/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

/**
 *
 * @author jafes
 */
public class FramePrincipalCliente extends javax.swing.JPanel {

    /**
     * Creates new form FramePrincipalCliente
     */
    public FramePrincipalCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pstPrnClienteGlobal = new javax.swing.JTabbedPane();
        pnlpstHacerPedido = new javax.swing.JPanel();
        lblTipoRestaurante = new javax.swing.JLabel();
        cbxTipoRestaurante = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantesG = new javax.swing.JTable();
        lblImagenRestaurantesG = new javax.swing.JLabel();
        pnlpstHistorialPedido = new javax.swing.JPanel();
        lblEstadoDelPedido = new javax.swing.JLabel();
        cbxEstadoDelPedido = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorialPedidos = new javax.swing.JTable();

        lblTipoRestaurante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipoRestaurante.setText("Tipo de Restaurante:");

        cbxTipoRestaurante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxTipoRestaurante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Tradicional", "Mexicano", "Oriental", " " }));

        tblRestaurantesG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE ", "CALLE", "CARRERA", "ACCION 1"
            }
        ));
        jScrollPane1.setViewportView(tblRestaurantesG);
        if (tblRestaurantesG.getColumnModel().getColumnCount() > 0) {
            tblRestaurantesG.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        javax.swing.GroupLayout pnlpstHacerPedidoLayout = new javax.swing.GroupLayout(pnlpstHacerPedido);
        pnlpstHacerPedido.setLayout(pnlpstHacerPedidoLayout);
        pnlpstHacerPedidoLayout.setHorizontalGroup(
            pnlpstHacerPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstHacerPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpstHacerPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpstHacerPedidoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(lblImagenRestaurantesG, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlpstHacerPedidoLayout.createSequentialGroup()
                        .addComponent(lblTipoRestaurante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        pnlpstHacerPedidoLayout.setVerticalGroup(
            pnlpstHacerPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstHacerPedidoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlpstHacerPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoRestaurante)
                    .addComponent(cbxTipoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlpstHacerPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagenRestaurantesG, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pstPrnClienteGlobal.addTab("HACER PEDIDO", pnlpstHacerPedido);

        lblEstadoDelPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstadoDelPedido.setText("Estado del pedido: ");

        cbxEstadoDelPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxEstadoDelPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Creado", "Pagado" }));

        tblHistorialPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RESTAURANTE", "FECHA CREADO", "FECHA PAGADO", "ACCION 1"
            }
        ));
        jScrollPane2.setViewportView(tblHistorialPedidos);

        javax.swing.GroupLayout pnlpstHistorialPedidoLayout = new javax.swing.GroupLayout(pnlpstHistorialPedido);
        pnlpstHistorialPedido.setLayout(pnlpstHistorialPedidoLayout);
        pnlpstHistorialPedidoLayout.setHorizontalGroup(
            pnlpstHistorialPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstHistorialPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpstHistorialPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpstHistorialPedidoLayout.createSequentialGroup()
                        .addComponent(lblEstadoDelPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxEstadoDelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        pnlpstHistorialPedidoLayout.setVerticalGroup(
            pnlpstHistorialPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstHistorialPedidoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlpstHistorialPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoDelPedido)
                    .addComponent(cbxEstadoDelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pstPrnClienteGlobal.addTab("HISTORIAL PEDIDO", pnlpstHistorialPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pstPrnClienteGlobal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pstPrnClienteGlobal)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxEstadoDelPedido;
    private javax.swing.JComboBox<String> cbxTipoRestaurante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEstadoDelPedido;
    private javax.swing.JLabel lblImagenRestaurantesG;
    private javax.swing.JLabel lblTipoRestaurante;
    private javax.swing.JPanel pnlpstHacerPedido;
    private javax.swing.JPanel pnlpstHistorialPedido;
    private javax.swing.JTabbedPane pstPrnClienteGlobal;
    private javax.swing.JTable tblHistorialPedidos;
    private javax.swing.JTable tblRestaurantesG;
    // End of variables declaration//GEN-END:variables
}
