/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.Factory;
import co.unicauca.microkernel.client.access.IClienteAccess;
import co.unicauca.microkernel.client.domain.clienteService;
import co.unicauca.microkernel.common.entities.CategoriaEnum;
import co.unicauca.microkernel.common.entities.PlatoEspecial;
import co.unicauca.microkernel.common.entities.RacionDia;
import gestionTabla.StructEspeciales;
import gestionTabla.StructRaciones;
import gestionTabla.TablaEspeciales;
import gestionTabla.TablaRaciones;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author EdynsonMJ
 */
public class FramePrincipalAdmin extends javax.swing.JFrame {

    //listas
    List<RacionDia> raciones;
    List<PlatoEspecial> especiales;
    //tablas
    TablaRaciones tabRaciones;
    TablaEspeciales tabEspeciales;
    //servicio
    IClienteAccess service;
    clienteService servicioRestaurante;

    /**
     * Creates new form FramePrincipalAdmin
     */
    public FramePrincipalAdmin() {
        try {
            //INSTANCIANDO EL SERVICIO, POR FABRICA
            service = Factory.getInstance().getClienteService();
            servicioRestaurante = new clienteService(service);
            //INICIALIZANDO TABLAS
            tabRaciones = new TablaRaciones();
            tabEspeciales = new TablaEspeciales();
            //INICIANDO COMPONENENTES
            initComponents();
            //INICIALIZANDO TABLAS Y LLENANDO LISTAS
            raciones = new ArrayList<>();
            especiales = new ArrayList<>();
            this.serviceListarRaciones();
            this.serviceListarEspeciales();
            //CREANDO TABLAS
            tabRaciones.ver_tabla(tblRaciones, raciones);
            tabEspeciales.ver_tabla(tblEspeciales, especiales);

        } catch (Exception ex) {
            Logger.getLogger(FramePrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpPestanias = new javax.swing.JTabbedPane();
        pnlInicio = new javax.swing.JPanel();
        lblImagenInicio = new javax.swing.JLabel();
        pnlInfoUsuario = new javax.swing.JPanel();
        lblImagenUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblNombreRestaurante = new javax.swing.JLabel();
        pnlRaciones = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRaciones = new javax.swing.JTable();
        lblImagenRacion = new javax.swing.JLabel();
        btnAgregarRacion = new javax.swing.JButton();
        pnlEspeciales = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEspeciales = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblImagenEspecial = new javax.swing.JLabel();
        pnlPedidos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreUsuario.setText("Nombre: ");

        lblNombreRestaurante.setText("Restaurante:");

        javax.swing.GroupLayout pnlInfoUsuarioLayout = new javax.swing.GroupLayout(pnlInfoUsuario);
        pnlInfoUsuario.setLayout(pnlInfoUsuarioLayout);
        pnlInfoUsuarioLayout.setHorizontalGroup(
            pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlInfoUsuarioLayout.setVerticalGroup(
            pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreRestaurante)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(pnlInfoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInfoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagenInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("INICIO", pnlInicio);

        lblFiltro.setText("Filtar por dia:");

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));

        tblRaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DIA", "TIPO", "PRECIO", "ACCION 1", "ACCION 2"
            }
        ));
        tblRaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRaciones);
        if (tblRaciones.getColumnModel().getColumnCount() > 0) {
            tblRaciones.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        btnAgregarRacion.setText("AGREGAR");

        javax.swing.GroupLayout pnlRacionesLayout = new javax.swing.GroupLayout(pnlRaciones);
        pnlRaciones.setLayout(pnlRacionesLayout);
        pnlRacionesLayout.setHorizontalGroup(
            pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRacionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRacionesLayout.createSequentialGroup()
                        .addComponent(lblFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImagenRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        pnlRacionesLayout.setVerticalGroup(
            pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltro))
                .addGap(18, 18, 18)
                .addGroup(pnlRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("RACIONES", pnlRaciones);

        tblEspeciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "PRECIO", "ACCION 1", "ACCION 1"
            }
        ));
        tblEspeciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEspecialesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEspeciales);
        if (tblEspeciales.getColumnModel().getColumnCount() > 0) {
            tblEspeciales.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jButton1.setText("AGREGAR");

        javax.swing.GroupLayout pnlEspecialesLayout = new javax.swing.GroupLayout(pnlEspeciales);
        pnlEspeciales.setLayout(pnlEspecialesLayout);
        pnlEspecialesLayout.setHorizontalGroup(
            pnlEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblImagenEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEspecialesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        pnlEspecialesLayout.setVerticalGroup(
            pnlEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagenEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("PLATOS ESPECIALES", pnlEspeciales);

        jLabel4.setText("PEDIDOS");

        javax.swing.GroupLayout pnlPedidosLayout = new javax.swing.GroupLayout(pnlPedidos);
        pnlPedidos.setLayout(pnlPedidosLayout);
        pnlPedidosLayout.setHorizontalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        pnlPedidosLayout.setVerticalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel4)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jtpPestanias.addTab("PEDIDOS", pnlPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpPestanias)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpPestanias, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRacionesMouseClicked
        int column = tblRaciones.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblRaciones.getRowHeight();
        byte[] imagen = this.raciones.get(row).getImagen();
        //INSTANCIAR IMAGEN

        this.fijarImagenRacion(imagen);

        if (row < tblRaciones.getRowCount() && row >= 0 && column < tblRaciones.getColumnCount() && column >= 0) {
            Object value = tblRaciones.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equals("modificar")) {
                    //es obtendra la informacion necesaria para construir un objeto que sera enviado a la interfaz modificar
                    System.out.println("Click en el boton modificar");
                    System.out.println(this.tblRaciones.getValueAt(row, StructRaciones.ID));
                    System.out.println(this.tblRaciones.getValueAt(row, StructRaciones.NOMBRE));
                    System.out.println(this.tblRaciones.getValueAt(row, StructRaciones.PRECIO));
                    System.out.println(this.tblRaciones.getValueAt(row, StructRaciones.TIPO));
                    System.out.println(this.tblRaciones.getValueAt(row, StructRaciones.DIA));
                }
                if (boton.getName().equals("eliminar")) {
                    int fila = tblRaciones.getSelectedRow();
                    System.out.println("valor " + tblRaciones.getValueAt(row, StructRaciones.NOMBRE));
                    JOptionPane.showConfirmDialog(null, "Desea eliminar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    System.out.println("Click en el boton eliminar" + evt.paramString());
                    //EVENTOS ELIMINAR
                }
            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tblRacionesMouseClicked

    private void tblEspecialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEspecialesMouseClicked
        int column = tblEspeciales.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblEspeciales.getRowHeight();

        if (row < tblEspeciales.getRowCount() && row >= 0 && column < tblEspeciales.getColumnCount() && column >= 0) {
            Object value = tblEspeciales.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equals("modificar")) {
                    //es obtendra la informacion necesaria para construir un objeto que sera enviado a la interfaz modificar
                    System.out.println("Click en el boton modificar");
                    System.out.println(this.tblEspeciales.getValueAt(row, StructEspeciales.ID));
                    System.out.println(this.tblEspeciales.getValueAt(row, StructEspeciales.NOMBRE));
                    System.out.println(this.tblEspeciales.getValueAt(row, StructEspeciales.PRECIO));
                    System.out.println(this.tblEspeciales.getValueAt(row, StructEspeciales.DESCRIPCION));
                    //EVENTOS MODIFICAR
                }
                if (boton.getName().equals("eliminar")) {
                    int fila = tblEspeciales.getSelectedRow();
                    System.out.println("valor " + tblEspeciales.getValueAt(row, StructRaciones.NOMBRE));
                    JOptionPane.showConfirmDialog(null, "Desea eliminar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    System.out.println("Click en el boton eliminar" + evt.paramString());
                    //EVENTOS ELIMINAR
                }
            }
            if (value instanceof JCheckBox) {
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tblEspecialesMouseClicked

    private void serviceListarRaciones() throws Exception {
        //el numero debe reemplazarse por el codigo del restaurante proveniente de la base de datos
        this.raciones = servicioRestaurante.listMenuDay(1, "LUNES", "administrador");
    }

    private void serviceListarEspeciales() throws Exception {
        //el numero debe reemplazarse por el codigo del restaurante proveniente de la base de datos
        this.especiales = servicioRestaurante.listMenuSpecial(1, "administrador");
    }

    private void fijarImagenRacion(byte[] imagen) {
        int alto = this.lblImagenRacion.getHeight();
        int ancho = this.lblImagenRacion.getWidth();
        int x = this.lblImagenRacion.getX();
        int y = this.lblImagenRacion.getY();
        if (imagen != null) {
            ImageIcon i = new ImageIcon(imagen);
            Image imgEscalada = i.getImage().getScaledInstance(this.lblImagenRacion.getWidth(),
                    this.lblImagenRacion.getHeight(), Image.SCALE_SMOOTH);
            Icon iconoEscalado = new ImageIcon(imgEscalada);
            this.lblImagenRacion.setIcon(iconoEscalado);
        } else {
            System.out.println("ingreo null");
            this.lblImagenRacion.setIcon(null);
            this.lblImagenRacion = new JLabel("No hay imagen");
            this.lblImagenRacion.setBounds(x, y, ancho, alto);
        }
    }

}

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalAdmin

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipalAdmin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRacion;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jtpPestanias;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblImagenEspecial;
    private javax.swing.JLabel lblImagenInicio;
    private javax.swing.JLabel lblImagenRacion;
    private javax.swing.JLabel lblImagenUsuario;
    private javax.swing.JLabel lblNombreRestaurante;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JPanel pnlEspeciales;
    private javax.swing.JPanel pnlInfoUsuario;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JPanel pnlRaciones;
    private javax.swing.JTable tblEspeciales;
    private javax.swing.JTable tblRaciones;
    // End of variables declaration//GEN-END:variables
}
