/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.IClienteAccess;
import co.unicauca.microkernel.client.domain.clienteService;
import co.unicauca.microkernel.client.gestionTabla.*;
import co.unicauca.microkernel.common.entities.*;
import java.util.List;

/**
 *
 * @author jafes
 */
public class HacerPedido extends javax.swing.JPanel {

    /**
     * Creates new form HacerPedido
     */
    public HacerPedido() {
        List<RacionDia> raciones;
        List<PlatoEspecial> especiales;
    //tablas
        TablaRaciones tabRaciones;
        TablaEspeciales tabEspeciales;
    //servicio
        IClienteAccess service;
        clienteService servicioRestaurante;
    //variables
       // private static String varDia;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pstHcPedidoGlobal = new javax.swing.JTabbedPane();
        pnlpstComprarRaciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRaciones = new javax.swing.JTable();
        lblImagenRacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarritoRaciones = new javax.swing.JTable();
        lblRaciones = new javax.swing.JLabel();
        lblCarritoRaciones = new javax.swing.JLabel();
        pnlpstComprarPlatos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEspeciales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCarritoPlatos = new javax.swing.JTable();
        lblPlatosEspeciales = new javax.swing.JLabel();
        lblCarritoPlatosEspeciales = new javax.swing.JLabel();
        pnlpstConfirmarPedido = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCarritoRacionesConfirmar = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCarritoPlatosConfirmar = new javax.swing.JTable();
        btnConfirmarPedido = new javax.swing.JButton();
        lblCarritoRacionesConfirmar = new javax.swing.JLabel();
        lblCarritoPlatosConfirmar = new javax.swing.JLabel();

        tblRaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DIA", "TIPO", "PRECIO", "ACCION 1"
            }
        ));
        jScrollPane1.setViewportView(tblRaciones);

        tblCarritoRaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD", "ACCION 1", "ACCION 2", "ACCION 2"
            }
        ));
        jScrollPane2.setViewportView(tblCarritoRaciones);

        lblRaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRaciones.setText("Raciones: ");

        lblCarritoRaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoRaciones.setText("Carrito de raciones: ");

        javax.swing.GroupLayout pnlpstComprarRacionesLayout = new javax.swing.GroupLayout(pnlpstComprarRaciones);
        pnlpstComprarRaciones.setLayout(pnlpstComprarRacionesLayout);
        pnlpstComprarRacionesLayout.setHorizontalGroup(
            pnlpstComprarRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstComprarRacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(lblImagenRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(pnlpstComprarRacionesLayout.createSequentialGroup()
                .addGroup(pnlpstComprarRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpstComprarRacionesLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(pnlpstComprarRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarritoRaciones)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlpstComprarRacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRaciones)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpstComprarRacionesLayout.setVerticalGroup(
            pnlpstComprarRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstComprarRacionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblRaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlpstComprarRacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagenRacion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblCarritoRaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblImagenRacion.getAccessibleContext().setAccessibleName("lblImagenRacion");

        pstHcPedidoGlobal.addTab("COMPRAR RACIONES", pnlpstComprarRaciones);

        tblEspeciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "PRECIO", "ACCION 1"
            }
        ));
        jScrollPane3.setViewportView(tblEspeciales);

        tblCarritoPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD", "ACCION 1", "ACCION 2", "ACCION 3"
            }
        ));
        jScrollPane4.setViewportView(tblCarritoPlatos);

        lblPlatosEspeciales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPlatosEspeciales.setText("Platos Especiales: ");

        lblCarritoPlatosEspeciales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoPlatosEspeciales.setText("Carrito de platos especiales: ");

        javax.swing.GroupLayout pnlpstComprarPlatosLayout = new javax.swing.GroupLayout(pnlpstComprarPlatos);
        pnlpstComprarPlatos.setLayout(pnlpstComprarPlatosLayout);
        pnlpstComprarPlatosLayout.setHorizontalGroup(
            pnlpstComprarPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstComprarPlatosLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(pnlpstComprarPlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlatosEspeciales)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlpstComprarPlatosLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(pnlpstComprarPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarritoPlatosEspeciales)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpstComprarPlatosLayout.setVerticalGroup(
            pnlpstComprarPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstComprarPlatosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblPlatosEspeciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlpstComprarPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblCarritoPlatosEspeciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pstHcPedidoGlobal.addTab("COMPRAR PLATOS ESPECIALES", pnlpstComprarPlatos);

        tblCarritoRacionesConfirmar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD"
            }
        ));
        tblCarritoRacionesConfirmar.setRequestFocusEnabled(false);
        jScrollPane5.setViewportView(tblCarritoRacionesConfirmar);

        tblCarritoPlatosConfirmar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CANTIDAD", "PRECIO"
            }
        ));
        jScrollPane6.setViewportView(tblCarritoPlatosConfirmar);

        btnConfirmarPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirmarPedido.setText("Confirmar Pedido");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });

        lblCarritoRacionesConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoRacionesConfirmar.setText("Carrito Raciones: ");

        lblCarritoPlatosConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoPlatosConfirmar.setText("Carrito Platos Especiales: ");

        javax.swing.GroupLayout pnlpstConfirmarPedidoLayout = new javax.swing.GroupLayout(pnlpstConfirmarPedido);
        pnlpstConfirmarPedido.setLayout(pnlpstConfirmarPedidoLayout);
        pnlpstConfirmarPedidoLayout.setHorizontalGroup(
            pnlpstConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpstConfirmarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpstConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarritoRacionesConfirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(pnlpstConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarritoPlatosConfirmar))
                .addContainerGap())
            .addGroup(pnlpstConfirmarPedidoLayout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(btnConfirmarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpstConfirmarPedidoLayout.setVerticalGroup(
            pnlpstConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpstConfirmarPedidoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlpstConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCarritoRacionesConfirmar)
                    .addComponent(lblCarritoPlatosConfirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlpstConfirmarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pstHcPedidoGlobal.addTab("CONFIRMAR PEDIDO", pnlpstConfirmarPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pstHcPedidoGlobal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pstHcPedidoGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCarritoPlatosConfirmar;
    private javax.swing.JLabel lblCarritoPlatosEspeciales;
    private javax.swing.JLabel lblCarritoRaciones;
    private javax.swing.JLabel lblCarritoRacionesConfirmar;
    private javax.swing.JLabel lblImagenRacion;
    private javax.swing.JLabel lblPlatosEspeciales;
    private javax.swing.JLabel lblRaciones;
    private javax.swing.JPanel pnlpstComprarPlatos;
    private javax.swing.JPanel pnlpstComprarRaciones;
    private javax.swing.JPanel pnlpstConfirmarPedido;
    private javax.swing.JTabbedPane pstHcPedidoGlobal;
    private javax.swing.JTable tblCarritoPlatos;
    private javax.swing.JTable tblCarritoPlatosConfirmar;
    private javax.swing.JTable tblCarritoRaciones;
    private javax.swing.JTable tblCarritoRacionesConfirmar;
    private javax.swing.JTable tblEspeciales;
    private javax.swing.JTable tblRaciones;
    // End of variables declaration//GEN-END:variables
}
